branch-defaults:
  master:
    environment: LowCost-env
environment-defaults:
  LowCost-env:
    branch: null
    repository: null
global:
  application_name: URL Shortener
  default_ec2_keyname: keypair
  default_platform: Node.js
  default_region: us-west-2
  profile: eb-cli
  sc: git
